"""Batch 02 lead data (25 Sep 2026). Single source for the batch doc and the Excel tracker."""

DATE = "2026-09-25"
BATCH = "02"

# confirmed = LinkedIn profile matched to this person through their own indexed posts.
# When False, the URL is a people-search link and the profile must be confirmed before sending.
LEADS = [
    # ---------------- India ----------------
    dict(name="Aniket Shah", role="Co-founder & CEO", company="Swish", region="India", city="Bengaluru",
         url="https://www.linkedin.com/in/aniketshah30", confirmed=True,
         trigger="$24M led by Bertelsmann India, with Accel and Bain Capital Ventures, to expand its 10-minute kitchen network", trigger_date="2026-09-10",
         source="https://entrackr.com/news/10-minute-food-delivery-startup-swish-raises-24-mn-led-by-bertelsmann-india-investments-12513814",
         pattern="Milestone-only", last_post="2025-03",
         activity="Indexed own posts: Founder's Office hiring (Jan 2025) and the last raise (Mar 2025). Co-founder Ujjwal Sukheja wrote the founding story the same week. Nothing indexed since.",
         angle="Quick commerce is crowded. The founder who explains why 10-minute fresh food works wins hires and press between rounds.",
         score=60,
         connect="Hi Aniket, congrats on the new round.\nNeighbourhood kitchens within a kilometre is a sharp way to make 10 minutes work.\nWould be good to connect.",
         dm="Thanks for connecting, Aniket.\nQuick one. With the kitchen network growing, do you want your own LinkedIn telling that story?\nOr is it mostly the brand account for now?",
         teardown="Posts only at raises and hiring; no view of his own on hyperlocal food ops; featured section not pointing to Swish.",
         notes="Co-founders Ujjwal Sukheja and Saran S. also post. Pitch Aniket first."),
    dict(name="Sunil Gupta", role="Co-founder & CEO", company="QNu Labs", region="India", city="Bengaluru",
         url="https://www.linkedin.com/in/sunil-gupta-1733754", confirmed=True,
         trigger="Rs 200 Cr Series A1 co-led by National Quantum Mission and Speciale Invest, with Sony Innovation Fund", trigger_date="2026-09-09",
         source="https://startuptalky.com/news/daily-indian-funding-roundup-key-news-9-september-2026/",
         pattern="Company-news voice", last_post="2025-12",
         activity="Posts company milestones one to three times a year since 2021: IMC 2022 (28 comments), India's first quantum telecom link, Tracxn ranking, a Dec 2025 breakthrough post. All announcements.",
         angle="Quantum security needs explaining to CISOs and government buyers. A founder voice on why quantum-safe matters now turns announcements into trust.",
         score=50,
         connect="Hi Sunil, congrats on the Series A1.\nQuantum-safe security built out of India is a story more CISOs should hear.\nWould be good to connect.",
         dm="Thanks for connecting, Sunil.\nYour posts mostly announce QNu milestones.\nHave you thought about explaining the why behind quantum-safe for buyers who are still catching up?",
         teardown="Announcement-only feed; no plain-language line on what QNu does; no cadence between milestones.",
         notes="Deep tech, government and defence buyers. Keep it formal."),
    dict(name="Prashant Shah", role="Co-founder", company="Definedge", region="India", city="Pune",
         url="https://www.linkedin.com/in/prashant-shah-definedge", confirmed=True,
         trigger="Rs 22 Cr pre-Series A; total raised Rs 30 Cr; 14+ trading and investing platforms (Opstra, Zone, Algostra)", trigger_date="2026-09-22",
         source="https://entrackr.com/snippets/fintech-and-brokerage-startup-definedge-raises-rs-22-cr-in-pre-series-a-12562400",
         pattern="Milestone-only", last_post="2025-12",
         activity="One own post indexed (Dec 2025, a Definedge milestone). Holds CMT, CFTe, MFTA and MSTA, so he has deep technical-analysis credibility that barely shows on LinkedIn.",
         angle="Retail traders follow people, not platforms. His chartered-technician credibility is the brand asset.",
         score=50,
         connect="Hi Prashant, congrats on the pre-Series A.\nFourteen platforms for retail traders out of Pune is a lot of product.\nWould be good to connect.",
         dm="Thanks for connecting, Prashant.\nYou carry more technical-analysis credentials than most people posting about markets.\nIs building a voice on LinkedIn part of the plan now?",
         teardown="Credentials in headline but no educational posts; no link to Definedge platforms; posts only at milestones.",
         notes="Check whether he already posts on YouTube or X. If so, pitch repurposing onto LinkedIn."),
    dict(name="Abhijit (AB) Gupta", role="Co-founder", company="Popo Global (The Pizza Bakery, Paris Panini, Smash Guys)", region="India", city="Bengaluru",
         url="https://www.linkedin.com/in/ab-gupta-9b1b8210", confirmed=True,
         trigger="Rs 532 Cr from Artal Asia to expand beyond Bengaluru", trigger_date="2026-09-11",
         source="https://entrackr.com/snippets/the-pizza-bakery-operator-popo-global-raises-rs-532-cr-from-artal-asia-12518089",
         pattern="Went quiet", last_post="2023-04",
         activity="Posted 'Growth Stories: Lessons from The Pizza Bakery' (Apr 2023) and spoke on an investor panel about building F&B without growth capital (May 2023). The company page carries it since.",
         angle="He built without outside capital and now has Rs 532 Cr. That's a founder story F&B operators and new-city hires will follow.",
         score=60,
         connect="Hi AB, congrats on the Artal round.\nBuilding The Pizza Bakery without growth capital first makes this one more interesting.\nWould be good to connect.",
         dm="Thanks for connecting, AB.\nYour growth-stories episode from 2023 was one of the few times you told the story yourself.\nWith new cities coming, is that something you want to do more of?",
         teardown="Three-year gap; profile doesn't show the three brands; expansion story is untold.",
         notes="Co-founder brother Nikhil Gupta. Pitch AB first."),
    dict(name="Karan Jain", role="Founder & CEO", company="Carrum Mobility", region="India", city="Bengaluru",
         url="https://www.linkedin.com/search/results/people/?keywords=Karan%20Jain%20Carrum%20Mobility", confirmed=False,
         trigger="$10M Series B led by Uber at about $168M valuation; business nearly doubled since January; profitable since month one", trigger_date="2026-09-09",
         source="https://techcrunch.com/2026/09/09/uber-invests-10m-in-indian-fleet-operator-carrum-at-168m-valuation/",
         pattern="Not indexed", last_post="",
         activity="No own posts indexed. Several people share the name, so confirm the profile first. He previously founded Revv (acquired by CarDekho).",
         angle="Second-time founder, profitable from month one, backed twice by Uber. A rare story in mobility that he isn't telling.",
         score=60,
         connect="Hi Karan, congrats on the Uber round.\nProfitable from month one in fleet management is rare. Following Carrum.\nWould be good to connect.",
         dm="Thanks for connecting, Karan.\nBetween Revv and Carrum you've got a founder story most people in mobility would want to hear.\nIs LinkedIn somewhere you want to tell it?",
         teardown="Confirm profile; check headline mentions Revv exit; content line on profitable fleet ops and the EV and CNG shift.",
         notes="Confirm profile before sending."),
    dict(name="Abhishek Murarka", role="Co-founder & CEO", company="Circolife", region="India", city="",
         url="https://www.linkedin.com/search/results/people/?keywords=Abhishek%20Murarka%20Circolife", confirmed=False,
         trigger="$4.5M (Rs 40.45 Cr) pre-Series A anchored by Bharat Jaisinghani of Polycab, with Nitish Mittersain; target 40,000 cooling units", trigger_date="2026-09-08",
         source="https://www.exchange4media.com/industry-briefing-news/circolife-raises-45-mn-pre-series-a-158085.html",
         pattern="Not indexed", last_post="",
         activity="Indexed posts under this name are about investing and wealth (2021 to 2024) and may be a different person. The Circolife company page posts regularly.",
         angle="Cooling-as-a-service is a new category. Businesses buying it want to trust the operator behind it.",
         score=50,
         connect="Hi Abhishek, congrats on the pre-Series A.\nCooling as a subscription is a smart model for Indian offices.\nWould be good to connect.",
         dm="Thanks for connecting, Abhishek.\nThe company page is doing the talking for Circolife right now.\nIs building your own voice around the category something you've thought about?",
         teardown="Confirm profile; company page posts, founder silent; content line on energy savings and IoT maintenance.",
         notes="Confirm profile before sending."),
    dict(name="Sneha Priya Reddy", role="Co-founder", company="UniqYou", region="India", city="Bengaluru",
         url="https://www.linkedin.com/search/results/people/?keywords=Sneha%20Priya%20Reddy%20UniqYou", confirmed=False,
         trigger="Rs 15.8 Cr seed led by Arkam Ventures and Antler; company founded 2026; angels include Myntra's co-founder and former CEO", trigger_date="2026-09-14",
         source="https://startuptalky.com/news/daily-indian-funding-roundup-key-news-14-september-2026/",
         pattern="Not indexed", last_post="",
         activity="No own posts indexed. Brand-new company, so her founder presence is starting from zero.",
         angle="Women's fashion is built on trust and taste. A founder-led feed at launch is cheaper than paid acquisition.",
         score=60,
         connect="Hi Sneha, congrats on the seed.\nA tech-first platform for women's fashion with the Myntra founders behind it is a strong start.\nWould be good to connect.",
         dm="Thanks for connecting, Sneha.\nIn fashion, people buy into the founder's taste first.\nIs your own LinkedIn part of the launch plan for UniqYou?",
         teardown="Confirm profile; launch story; build-in-public format for the first 90 days.",
         notes="Confirm profile. Co-founder Nishanth Jois."),
    dict(name="Ankit Joshi", role="Co-founder", company="TRUE ARTIS", region="India", city="Delhi NCR",
         url="https://www.linkedin.com/search/results/people/?keywords=Ankit%20Joshi%20TRUE%20ARTIS", confirmed=False,
         trigger="Rs 11.4 Cr seed led by Zeropearl VC, with Medanta co-founder's group Eleven; two aesthetic surgery centres in Delhi and Gurgaon", trigger_date="2026-09-16",
         source="https://startuptalky.com/news/daily-indian-funding-roundup-key-news-16-september-2026/",
         pattern="Not indexed", last_post="",
         activity="No own posts indexed that clearly match. Many profiles share the name.",
         angle="Aesthetic surgery is a trust purchase. A founder who explains safety and standards sets the brand apart from clinics.",
         score=50,
         connect="Hi Ankit, congrats on the seed.\nAn integrated aesthetic surgery platform with Medanta-linked backing is a strong signal.\nWould be good to connect.",
         dm="Thanks for connecting, Ankit.\nIn aesthetics, patients check who's behind the clinic before they book.\nIs founder content part of how you want to build TRUE ARTIS?",
         teardown="Confirm profile; trust and safety content line; doctor partner features.",
         notes="Confirm profile. Co-founder Sandeep Upadhyay. Medical advertising rules apply to content."),
    dict(name="Devang Kumar", role="Founder & CEO", company="Greenwave Circularity", region="India", city="Odisha",
         url="https://www.linkedin.com/search/results/people/?keywords=Devang%20Kumar%20Greenwave%20Circularity", confirmed=False,
         trigger="$31.5M financing from OeEB (Development Bank of Austria) for a closed-loop PET recycling plant; JV with a Coca-Cola bottler", trigger_date="2026-09-09",
         source="https://indianstartupnews.com/funding/greenwave-circularity-raises-315-million-from-oeeb-for-odisha-pet-recycling-plant-12516293",
         pattern="Not indexed", last_post="",
         activity="No own posts indexed.",
         angle="Circular economy buyers (brands, bottlers, ESG teams) look for credible operators. A founder voice on recycled PET fills that gap.",
         score=50,
         connect="Hi Devang, congrats on the OeEB financing.\nClosed-loop PET recycling at that scale is what brand ESG targets need.\nWould be good to connect.",
         dm="Thanks for connecting, Devang.\nMost brand sustainability leads are on LinkedIn.\nIs building a voice there part of how you plan to win offtake partners?",
         teardown="Confirm profile; ESG buyer content line; plant progress series.",
         notes="Confirm profile. This is debt financing, not equity, so avoid calling it a round."),
    dict(name="Avni Jain", role="Founder", company="Nuvah", region="India", city="",
         url="https://www.linkedin.com/search/results/people/?keywords=Avni%20Jain%20Nuvah", confirmed=False,
         trigger="Rs 4 Cr pre-seed from Amit Jain (CarDekho), Shantanu Deshpande (Bombay Shaving Co) and Ishendra Agarwal (GIVA); comfort-engineered heels", trigger_date="2026-09-22",
         source="https://startuptalky.com/news/nuvah-raises-4-crore-pre-seed-comfort-heels/",
         pattern="Not indexed", last_post="",
         activity="No own posts indexed that match. Ex-McKinsey, Goldman Sachs and VC; IIM Ahmedabad.",
         angle="D2C founder with a product-obsession story (24 prototypes, 900 hours of wear testing). That's content.",
         score=50,
         connect="Hi Avni, congrats on the pre-seed.\n24 prototypes to get a heel that doesn't hurt is the kind of detail that sells.\nWould be good to connect.",
         dm="Thanks for connecting, Avni.\nThe build story behind Nuvah is strong content on its own.\nIs founder-led content part of the launch plan?",
         teardown="Confirm profile; build-in-public series; headline from consulting to founder.",
         notes="Confirm profile. Pre-seed budget, so offer the pilot."),

    # ---------------- UK ----------------
    dict(name="Charlie Bullock", role="Co-founder & CEO", company="Scan.com", region="UK", city="London",
         url="https://www.linkedin.com/in/charlie-bullock", confirmed=True,
         trigger="$220M incl. $90M Series C equity led by Noteus Partners, to build the largest US imaging network", trigger_date="2026-08-31",
         source="https://www.businesswire.com/news/home/20260831019981/en/Scan.com-Raises-$220-Million-to-Build-the-Largest-Medical-Imaging-Network-in-the-US",
         pattern="Milestone-only", last_post="2025-03",
         activity="Forbes 30 Under 30 (Apr 2024), Deloitte recognition (Nov 2024), a healthtech diagnostics post with 59 comments (Mar 2025). Last own post indexed Mar 2025.",
         angle="Moving the centre of gravity to the US. US health systems and partners don't know him yet.",
         score=60,
         connect="Hi Charlie, congrats on the Series C.\nBuilding a national imaging network in the US from a UK start is a big move.\nWould be good to connect.",
         dm="Thanks for connecting, Charlie.\nYour posts do well when you post. The last one I could find was March 2025.\nWith the US push, is getting back to it on the list?",
         teardown="18-month gap; UK framing; US health-system audience content line.",
         notes="Likely has comms support. Ask who owns his LinkedIn."),
    dict(name="Charlie Cook", role="Founder & CEO", company="Rightcharge", region="UK", city="London",
         url="https://www.linkedin.com/in/charlie-cook-2088922b", confirmed=True,
         trigger="GBP 500k after 20x ARR growth, to scale fleet EV charging payments across Europe; Visa recommended partner (Jul 2026)", trigger_date="2026-09-03",
         source="https://tech.eu/2026/09/03/rightcharge-raises-ps500k-to-scale-fleet-ev-charging-payments-across-europe",
         pattern="Emerging writer", last_post="2026-07",
         activity="Posts a few times a year with some humour: an April Fools 'former CEO resigns' post (1 Apr 2025), how his team uses AI (Jun 2025), Visa partnership (Jul 2026).",
         angle="Already has a voice and a sense of humour. The gap is cadence as he enters Europe.",
         score=50,
         connect="Hi Charlie, congrats on the raise and the Visa partnership.\nFleet charging payments is a real headache for operators.\nWould be good to connect.",
         dm="Thanks for connecting, Charlie.\nYou've got a voice on LinkedIn, it just shows up a few times a year.\nWith Europe coming, is more regular posting worth it to you?",
         teardown="Cadence; European fleet-manager audience; one recurring format.",
         notes="The 'resigns' post is an April Fools joke. He's still CEO."),
    dict(name="Koji Muto", role="Co-founder & CEO", company="Ki 13 (formerly Ki Hydrogen)", region="UK", city="London",
         url="https://www.linkedin.com/in/kojimuto", confirmed=True,
         trigger="$5M seed led by HICO, plus Innovate UK grants; rebranded to Ki 13 (Aug 2026)", trigger_date="2026-09",
         source="https://www.finsmes.com/2026/09/ki-13-raises-5m-in-seed-funding.html",
         pattern="Milestone-only", last_post="2026-08",
         activity="Business-plan competitions (2023), pitch video (21 comments), green hydrogen post (Apr 2024), rebrand (Aug 2026). Posts around milestones only.",
         angle="Deep climate tech with a new name. The rebrand needs a founder narrative to stick.",
         score=60,
         connect="Hi Koji, congrats on the seed and the new Ki 13 name.\nProducing green hydrogen and biogenic CO2 together is a clever angle.\nWould be good to connect.",
         dm="Thanks for connecting, Koji.\nA rebrand plus a raise is a good moment to set the story.\nIs your own LinkedIn part of how you want to do that?",
         teardown="Headline still reads Ki Hydrogen (check); milestone-only cadence; explainer series.",
         notes=""),
    dict(name="Francisco Vigo", role="Co-founder & CEO", company="geoSurge", region="UK", city="London",
         url="https://www.linkedin.com/in/francisco-juan-vigo", confirmed=True,
         trigger="$12M (EUR 10M) seed led by AlbionVC with Play Ventures", trigger_date="2026-07-03",
         source="https://www.uktech.news/ai/ai-search-visibility-startup-geosurge-scores-9-4m-round-20260703",
         pattern="Company-page voice", last_post="2025-12",
         activity="One own post indexed (Dec 2025, launch). The company page and London Stock Exchange's The Stage feature him (Feb to Mar 2026).",
         angle="geoSurge sells AI visibility. LinkedIn posts are one of the sources AI models cite, so his own visibility is on-message.",
         score=50,
         connect="Hi Francisco, congrats on the seed.\nHelping brands see how AI models describe them is a real new need.\nWould be good to connect.",
         dm="Thanks for connecting, Francisco.\nOdd question for someone in AI visibility. How visible do you want to be yourself?\nThe company page is doing most of the talking.",
         teardown="Company page vs founder feed; LinkedIn as an AI-citation source; weekly insight format.",
         notes=""),
    dict(name="Callum Adamson", role="Co-founder & CEO", company="Applied Computing", region="UK", city="London",
         url="https://www.linkedin.com/in/callumadamson", confirmed=True,
         trigger="About EUR 17.4M led by KBR with Databricks Ventures; Orbital foundation model for energy operators", trigger_date="2026-07-15",
         source="https://techcrunch.com/2026/07/15/applied-computing-wants-to-give-oil-and-gas-operators-an-ai-model-for-the-entire-plant/",
         pattern="Went quiet", last_post="2025-05",
         activity="Earlier career posts (Distributed, recruiting). A Fred Destin venture post (Nov 2024), an Applied Computing post (May 2025). The company page carries podcasts and Orbital since.",
         angle="Energy operators buy from people they trust. A CEO voice on AI in refining is rare and credible.",
         score=50,
         connect="Hi Callum, congrats on the round with KBR and Databricks.\nA foundation model for a whole plant is a bold scope.\nWould be good to connect.",
         dm="Thanks for connecting, Callum.\nThe Orbital story is mostly on the company page.\nIs building your own voice with energy operators on the list?",
         teardown="16-month gap; headline; operator-facing content line.",
         notes="Co-founder Dr Sam Tukra."),
    dict(name="Lestat McCree", role="Co-founder & CEO", company="Healf", region="UK", city="London",
         url="https://www.linkedin.com/in/lestatmccree", confirmed=True,
         trigger="Funding led by SEMCAP Beauty & Wellness; GBP 100M+ annualised revenue; expanding to Germany", trigger_date="2026-08-31",
         source="https://www.globenewswire.com/news-release/2026/08/31/3353334/0/en/semcap-beauty-wellness-leads-funding-round-for-healf.html",
         pattern="Emerging writer", last_post="2026-01",
         activity="Occasional essays (work-life balance, Jan 2026). A piece on AI adoption drew reaction posts from others (Jun 2026). Covered by The Times. Few own posts overall.",
         angle="He writes well when he writes. International expansion plus press momentum is the moment to post weekly.",
         score=50,
         connect="Hi Lestat, congrats on the round and the Germany launch.\nGBP 100M with under 100 people is a remarkable ratio.\nWould be good to connect.",
         dm="Thanks for connecting, Lestat.\nYour AI adoption piece got people talking, but it's one of only a few posts.\nIs a steadier cadence worth it to you now?",
         teardown="Cadence; German market framing; recurring founder essay.",
         notes="Co-founder Max Clarke. Big brand, so expect a comms team."),
    dict(name="Jon Steinback", role="Co-founder & CEO", company="Marker", region="UK", city="London",
         url="https://www.linkedin.com/in/itsmejon", confirmed=True,
         trigger="$13M seed led by Index Ventures with LocalGlobe; AI-native word processor", trigger_date="2026-07-09",
         source="https://tech.eu/2026/07/09/ai-writing-startup-co-founded-by-deepmind-creative-lead-raises-13m-seed-investment/",
         pattern="Already consistent", last_post="2026-07",
         activity="Ex-DeepMind brand and creative lead. Launch posts (Apr and Jul 2026, 16 comments), 'AI writing app fighting AI slop' (Jul 2026). Writes his own posts.",
         angle="He won't want a ghostwriter. Pitch strategy, distribution and time back, not writing.",
         score=40,
         connect="Hi Jon, congrats on the Marker launch.\nA word processor that writes with you, not for you, is a stance I agree with.\nWould be good to connect.",
         dm="Thanks for connecting, Jon.\nYou clearly write your own posts, and should.\nCurious whether distribution and cadence are the harder part right now?",
         teardown="Distribution not writing; cadence; audience of writers vs buyers.",
         notes="Low fit for ghostwriting. Only pitch strategy."),
    dict(name="Stephen Cowley", role="Co-founder", company="Pharosyn", region="UK", city="London",
         url="https://www.linkedin.com/in/stephen-cowley-8960a0228", confirmed=True,
         trigger="$3M (EUR 2.5M) seed led by Moonfire Ventures, with Entrepreneurs First", trigger_date="2026-09-04",
         source="https://www.eu-startups.com/2026/09/uk-startup-pharosyn-raises-e2-5-million-for-pharma-competitive-intelligence-platform",
         pattern="Emerging writer", last_post="2026-07",
         activity="Two customer-story posts (Jun and Jul 2026) about onboarding calls and report quality. New to posting.",
         angle="Pharma commercial teams are on LinkedIn. He's started posting customer stories; the gap is consistency.",
         score=40,
         connect="Hi Stephen, congrats on the seed.\nCompetitive intelligence built into pharma commercial teams is an underserved corner.\nWould be good to connect.",
         dm="Thanks for connecting, Stephen.\nYou've started posting customer stories, which is the right instinct.\nIs keeping that going every week realistic with everything else?",
         teardown="Cadence; pharma buyer framing; customer-story series.",
         notes="Confirm who's CEO (Stephen or Joshua Hampson)."),
    dict(name="Steve Rimmer", role="CEO", company="Tickets for Good", region="UK", city="",
         url="https://www.linkedin.com/search/results/people/?keywords=Steve%20Rimmer%20Tickets%20for%20Good", confirmed=False,
         trigger="GBP 3.9M new funding; platform giving NHS workers, teachers and charity staff access to surplus event tickets", trigger_date="2026-09",
         source="https://www.finsmes.com/2026/09/tickets-for-good-raises-3-9m-in-new-funding.html",
         pattern="Not indexed", last_post="",
         activity="No confirmed own posts. A 2023 post about leaving a role may be his. The company page ran a founder interview (2025).",
         angle="A social-impact brand with a feel-good story. Partners (venues, promoters) and members respond to the founder.",
         score=50,
         connect="Hi Steve, congrats on the new funding.\nGetting surplus tickets to key workers is a lovely model.\nWould be good to connect.",
         dm="Thanks for connecting, Steve.\nTickets for Good has the kind of story people share.\nIs your own LinkedIn part of how you tell it to venues and promoters?",
         teardown="Confirm profile; impact stories series; partner-facing content.",
         notes="Confirm profile and whether he's the founder."),
    dict(name="Ismaeel Bashir", role="Co-founder & CEO", company="Expanse", region="UK", city="London / US",
         url="https://www.linkedin.com/search/results/people/?keywords=Ismaeel%20Bashir%20Expanse", confirmed=False,
         trigger="EUR 4.5M for a predictive AI infrastructure platform", trigger_date="2026-09",
         source="https://www.eu-startups.com/2026/09/u-s-and-u-k-based-expanse-raises-e4-5-million-for-predictive-ai-infrastructure-platform",
         pattern="Not indexed", last_post="",
         activity="No own posts indexed.",
         angle="AI infrastructure is noisy. A founder with a clear point of view stands out to buyers and hires in both markets.",
         score=50,
         connect="Hi Ismaeel, congrats on the raise.\nPredictive AI infrastructure is a busy space. Following Expanse.\nWould be good to connect.",
         dm="Thanks for connecting, Ismaeel.\nWith teams in the UK and US, is LinkedIn part of how you want buyers on both sides to know you?",
         teardown="Confirm profile; point-of-view content line; dual-market framing.",
         notes="Confirm profile and base (UK or US)."),

    # ---------------- Canada ----------------
    dict(name="Jason Liao", role="Co-founder & CEO", company="Mundo AI", region="Canada", city="Vancouver",
         url="https://www.linkedin.com/search/results/people/?keywords=Jason%20Liao%20Mundo%20AI", confirmed=False,
         trigger="$20M Series A led by GreatPoint Ventures plus a $4M seed; YC; data for AI perception (audio, video)", trigger_date="2026-09-02",
         source="https://betakit.com/mundo-announces-24-million-usd-to-help-tackle-ais-next-frontier/",
         pattern="Not indexed", last_post="",
         activity="No own posts indexed. Co-founder Garreth Lee posted the founding news (Feb 2025).",
         angle="AI data infrastructure buyers (labs, model teams) need to trust the team. A CEO voice on perception data is thin in the market.",
         score=50,
         connect="Hi Jason, congrats on the Series A.\nTraining data for AI beyond text is where a lot of the next gains are.\nWould be good to connect.",
         dm="Thanks for connecting, Jason.\nMost of Mundo's story online comes from your co-founders or press.\nIs your own voice something you want to build now?",
         teardown="Confirm profile; research-to-buyer content line; hiring angle.",
         notes="Confirm profile."),
    dict(name="David S. Bennahum", role="Co-founder & CEO", company="Onix", region="Canada", city="Ottawa",
         url="https://www.linkedin.com/in/dbennahum", confirmed=True,
         trigger="$5M pre-seed led by Alpha Edison; AI versions of health and wellness experts", trigger_date="2026-09-10",
         source="https://betakit.com/onix-raises-5-million-usd-to-create-ai-library-of-health-and-wellness-experts/",
         pattern="Emerging writer", last_post="2025-09",
         activity="Posts every few months (gaming, Web3, NotebookLM, a Delaware court post, Onix launch Sep 2025). Former WIRED contributing editor.",
         angle="He can write. His product is built on experts' voices, so a strong founder voice fits. Pitch cadence and strategy.",
         score=40,
         connect="Hi David, congrats on the pre-seed.\nAI built on licensed expert knowledge instead of the average internet is a clear stance.\nWould be good to connect.",
         dm="Thanks for connecting, David.\nOnix is built on experts owning their voice. Yours shows up every few months.\nIs a steadier cadence worth it with the raise done?",
         teardown="Cadence; Onix positioning in headline; expert-partner content.",
         notes="Writer himself, so pitch strategy over ghostwriting."),
    dict(name="Kyle Braatz", role="Co-founder & CEO", company="Fullscript", region="Canada", city="Ottawa",
         url="https://www.linkedin.com/in/braatzy", confirmed=True,
         trigger="Investment from L Catterton and Altas Partners", trigger_date="2026-09",
         source="https://www.finsmes.com/2026/09/fullscript-receives-investment.html",
         pattern="Company-news voice", last_post="2026-02",
         activity="Posts two to four times a year: labs launch, Fullscript Wrapped, engineering 'Builder's Corner' (Feb 2026), the $300M raise (2021, 43 comments). Ottawa CEO of the Year 2022.",
         angle="Large company with a practitioner audience. A CEO point of view on integrative health would lift a company-news feed.",
         score=50,
         connect="Hi Kyle, congrats on the L Catterton and Altas investment.\nFullscript's growth out of Ottawa has been fun to follow.\nWould be good to connect.",
         dm="Thanks for connecting, Kyle.\nYour feed is mostly Fullscript updates.\nIs a stronger personal point of view something you'd want now?",
         teardown="Company-news only; practitioner-facing content line; cadence.",
         notes="Likely has an in-house comms team. Pitch executive content support."),
    dict(name="LP Maurice", role="Co-founder & CEO", company="Busbud / Terra Mobility", region="Canada", city="Montreal",
         url="https://www.linkedin.com/in/lmaurice", confirmed=True,
         trigger="US$40M financing from Vista Credit Partners and launch of parent company Terra Mobility", trigger_date="2026-08",
         source="https://www.finsmes.com/2026/08/busbud-raises-40m-in-funding.html",
         pattern="Went quiet", last_post="2024-05",
         activity="Strong engagement when he posts: $11M raise (60 comments), LatAm (64 comments), Betterez deal, Africa B2B (May 2024). Nothing indexed since.",
         angle="He knows posting works. A new parent company is the moment to restart.",
         score=60,
         connect="Hi LP, congrats on the financing and the Terra Mobility launch.\nBusbud's reach into LatAm and Africa is impressive.\nWould be good to connect.",
         dm="Thanks for connecting, LP.\nYour LatAm and Africa posts got real engagement, then things went quiet.\nWith Terra Mobility launching, is restarting on the list?",
         teardown="Two-year gap; Terra Mobility not in headline (check); global mobility content line.",
         notes="Montreal. Offer French."),
    dict(name="Stéphane Garneau", role="President & CEO", company="Micrologic", region="Canada", city="Montreal",
         url="https://www.linkedin.com/in/sgarneau", confirmed=True,
         trigger="$45M from Fonds de solidarité FTQ and Investissement Québec for sovereign cloud services", trigger_date="2026",
         source="https://betakit.com/micrologic-raises-45-million-for-sovereign-cloud-services/",
         pattern="Went quiet", last_post="2024-05",
         activity="Posts in French on sovereign cloud, culture and HR (2022 to 2024), a 2023 year-in-review, CEO of the Year 2023. Nothing indexed since May 2024.",
         angle="Sovereign cloud is a live policy topic. A CEO voice in French and English positions Micrologic with public-sector buyers.",
         score=50,
         connect="Bonjour Stéphane, félicitations pour le financement.\nLe cloud souverain est un sujet de plus en plus important.\nAu plaisir d'échanger.",
         dm="Merci pour la connexion, Stéphane.\nVous publiiez régulièrement sur le cloud souverain, puis plus rien depuis 2024.\nEst-ce que reprendre fait partie des plans?",
         teardown="Two-year gap; bilingual content; public-sector buyer framing.",
         notes="Confirm the funding date before sending. Write in French."),
    dict(name="Sanja Fidler", role="Co-founder & CEO", company="Veeda AI", region="Canada", city="Toronto",
         url="https://www.linkedin.com/in/sanja-fidler-2846a1a", confirmed=True,
         trigger="$90M+ seed from Khosla Ventures and Radical Ventures; left NVIDIA (VP AI research) to found Veeda", trigger_date="2026-08",
         source="https://www.finsmes.com/2026/08/veeda-innovation-raises-over-90m-in-seed-funding.html",
         pattern="Research voice", last_post="2025-12",
         activity="Posts research releases from NVIDIA a few times a year (40 comments on one in Sep 2025). Last indexed Dec 2025, before Veeda.",
         angle="From NVIDIA researcher to founder. Hiring world-class researchers depends on her voice.",
         score=50,
         connect="Hi Sanja, congrats on launching Veeda.\nWorld models for physical reality is a big bet with the right team behind it.\nWould be good to connect.",
         dm="Thanks for connecting, Sanja.\nYour feed has been NVIDIA research. Veeda is a new story.\nIs your LinkedIn part of how you want to recruit for it?",
         teardown="Headline and feed still NVIDIA (check); founder narrative; research hiring content.",
         notes="High profile. Low odds, high value."),
    dict(name="Kimia Hamidi", role="Co-founder & CEO", company="NationGraph", region="Canada", city="Toronto / SF",
         url="https://www.linkedin.com/in/hkimia", confirmed=True,
         trigger="$18M Series A led by Menlo Ventures (announced Feb 2026; older than 90 days)", trigger_date="2026-02-25",
         source="https://www.axios.com/pro/enterprise-software-deals/2026/02/25/govtech-nationgraph-18-million-menlo",
         pattern="Emerging writer", last_post="2026-04",
         activity="Product and fundraise posts: Feb 2025 launch (82 comments), $4.5M (Aug 2025), product post (Apr 2026).",
         angle="Govtech sales need trust with public-sector buyers. His posts do well but come a few times a year.",
         score=20,
         connect="Hi Kimia, NationGraph's public-sector data work is interesting to follow.\nWould be good to connect.",
         dm="Thanks for connecting, Kimia.\nYour launch post drew a lot of discussion.\nIs a regular cadence worth building now?",
         teardown="Cadence; public-sector buyer content.",
         notes="Nurture. Trigger is older than 90 days. Revisit on the next trigger."),
    dict(name="Darren Hill", role="CEO", company="Legio", region="Canada", city="Toronto",
         url="https://www.linkedin.com/search/results/people/?keywords=Darren%20Hill%20Legio", confirmed=False,
         trigger="$5M seed from Klass Capital; AI safety and security operations for higher education", trigger_date="2026-08",
         source="https://www.finsmes.com/2026/08/legio-raises-5m-in-seed-funding.html",
         pattern="Not indexed", last_post="",
         activity="Several profiles share the name. One 'co-founder' Darren Hill posts on tech adoption, but it's not confirmed.",
         angle="University safety leaders buy on trust. A founder voice on campus safety sets Legio apart.",
         score=50,
         connect="Hi Darren, congrats on the seed.\nSafety operations built for campuses is a focused bet.\nWould be good to connect.",
         dm="Thanks for connecting, Darren.\nCampus safety leaders are a tight community.\nIs LinkedIn part of how you want to reach them?",
         teardown="Confirm profile; higher-ed buyer content line.",
         notes="Confirm profile."),
    dict(name="Kelvin Cui", role="Co-founder & CEO", company="Peripheral", region="Canada", city="Toronto",
         url="https://www.linkedin.com/search/results/people/?keywords=Kelvin%20Cui%20Peripheral", confirmed=False,
         trigger="$8.7M seed led by Inovia Capital and Deloitte Ventures, with Khosla Ventures; AI spatial intelligence for live sports media", trigger_date="2026-08",
         source="https://www.finsmes.com/2026/08/peripheral-raises-8-7m-in-seed-funding.html",
         pattern="Not indexed", last_post="",
         activity="No recent own posts indexed.",
         angle="Sports media is a visual, shareable space. A founder feed with product clips does double duty as marketing.",
         score=50,
         connect="Hi Kelvin, congrats on the seed.\nSpatial intelligence for live sports is a fun problem.\nWould be good to connect.",
         dm="Thanks for connecting, Kelvin.\nYour product is very visual, which suits LinkedIn.\nIs founder content part of the go-to-market?",
         teardown="Confirm profile; product-clip content series.",
         notes="Confirm profile. Co-founder Mustafa Khan."),
    dict(name="Sumit Ajwani", role="Founder & CEO", company="MakeOS (Makers)", region="Canada", city="Toronto",
         url="https://www.linkedin.com/in/sumitproducer", confirmed=True,
         trigger="Launched MakeOS, an AI workspace for producers", trigger_date="2026-08-17",
         source="https://lbbonline.com/news/sumit-ajwani-makeos-ai-workspace-producers",
         pattern="Not indexed", last_post="",
         activity="Profile found, but no own posts indexed. The Makers company page announced MakeOS.",
         angle="Producers and agencies are a LinkedIn-native audience. A founder voice on AI in production fits.",
         score=50,
         connect="Hi Sumit, congrats on launching MakeOS.\nAn AI workspace built for producers is overdue.\nWould be good to connect.",
         dm="Thanks for connecting, Sumit.\nThe launch is on the Makers page. Your own feed is quiet.\nIs that something you want to change for MakeOS?",
         teardown="Founder feed silent; producer-audience content line.",
         notes="Launch, not a funding round. Check whether there was a raise."),

    # ---------------- US ----------------
    dict(name="Baker Shogry", role="Co-founder & CEO", company="Light", region="US", city="",
         url="https://www.linkedin.com/in/bakershogry", confirmed=True,
         trigger="$46M Series A; white-label retail electricity platform", trigger_date="2026-09",
         source="https://www.finsmes.com/2026/09/light-raises-46m-in-series-a-funding.html",
         pattern="Near-silent", last_post="2021-12",
         activity="One own post indexed (Plaid FinRise, Dec 2021). Co-launched a heat pump project with Calvin French-Owen (2022).",
         angle="Energy is a trust category. A $46M Series A with a near-silent founder is a clear gap.",
         score=50,
         connect="Hi Baker, congrats on the Series A.\nLetting any brand launch its own electricity plan is a clever wedge.\nWould be good to connect.",
         dm="Thanks for connecting, Baker.\nYou've been pretty quiet on here.\nWith the Series A done, is building a voice in energy something you'd want?",
         teardown="Near-silent feed; headline; energy-transition content line.",
         notes=""),
    dict(name="Guy Shahar", role="Co-founder & CEO", company="Blee", region="US", city="",
         url="https://www.linkedin.com/in/guy-shahar", confirmed=True,
         trigger="$20M Series A; AI marketing compliance; grew 10x in 2025", trigger_date="2026-09-08",
         source="https://www.finsmes.com/2026/09/blee-raises-20m-in-series-a-funding.html",
         pattern="Already consistent", last_post="2026-09",
         activity="Roughly monthly since 2025: NerdWallet partnership, Figma plugin, 10x growth hiring post, case studies, Series A (8 Sep 2026).",
         angle="Already posting. Pitch reach and time back as the company scales.",
         score=40,
         connect="Hi Guy, congrats on the Series A.\nThe NerdWallet partnership was a strong proof point for Blee.\nWould be good to connect.",
         dm="Thanks for connecting, Guy.\nYou post more consistently than most founders.\nHow much of your week does it take right now?",
         teardown="Reach vs frequency; repurposing; compliance-leader audience.",
         notes="Active in the last 30 days."),
    dict(name="Michael LaFramboise", role="Co-founder & CEO", company="Aurelius Systems", region="US", city="San Francisco",
         url="https://www.linkedin.com/in/michael-laframboise", confirmed=True,
         trigger="$40M Series A; directed-energy counter-drone systems", trigger_date="2026-08-05",
         source="https://www.finsmes.com/2026/08/aurelius-systems-raises-40m-in-series-a-funding.html",
         pattern="Emerging writer", last_post="2026-04",
         activity="Posts every one to three months: 'our startup shoots down drones with lasers' (Feb 2025), DragonFire (Jul 2025), careers, Archimedes manufacturing (Apr 2026).",
         angle="Defence tech buyers and recruits follow founders. He has the voice; cadence and reach are the gap.",
         score=40,
         connect="Hi Michael, congrats on the Series A.\nUS-made directed energy for counter-drone is a timely bet.\nWould be good to connect.",
         dm="Thanks for connecting, Michael.\nYour posts on defence tech get attention when they land.\nIs going weekly worth it for hiring and customers?",
         teardown="Cadence; defence buyer content; hiring series.",
         notes="Defence content has rules. Check export and ITAR boundaries."),
    dict(name="Noah Schochet", role="Co-founder & CEO", company="TerraFirma", region="US", city="Austin",
         url="https://www.linkedin.com/in/noahschochet", confirmed=True,
         trigger="$100M+ Series A led by Kleiner Perkins; tech-enabled construction", trigger_date="2026-07-14",
         source="https://www.finsmes.com/2026/07/terrafirma-raises-100m-in-series-a-funding.html",
         pattern="Emerging writer", last_post="2026-07",
         activity="Opinion posts every two to three months in 2026: 'stop shipping software' (Feb), 'the future is already here' (Apr), Series A (Jul).",
         angle="A strong contrarian point of view on construction. More frequency turns it into a category voice.",
         score=40,
         connect="Hi Noah, congrats on the Series A.\nSaw your 'stop shipping software' post. Not a line I expected from a construction company.\nWould be good to connect.",
         dm="Thanks for connecting, Noah.\nYour posts have a clear point of view. They come every couple of months.\nWould going weekly change anything for hiring or deals?",
         teardown="Cadence; construction-buyer framing; recurring format.",
         notes=""),
    dict(name="Christian Bhatia Ondaatje", role="CEO", company="Aranya", region="US", city="",
         url="https://www.linkedin.com/in/christianondaatje", confirmed=True,
         trigger="$11M; clusterdOS turns bare metal into production clusters in under 48 hours", trigger_date="2026-09",
         source="https://www.finsmes.com/2026/09/aranya-raises-11m-in-funding.html",
         pattern="Near-silent", last_post="2024-12",
         activity="One own post indexed (Dec 2024). Company announced 'out of stealth' (Apr 2026). Co-founder Aryamika posts more.",
         angle="AI infrastructure buyers need to trust the CEO. Coming out of stealth plus a raise is the moment.",
         score=50,
         connect="Hi Christian, congrats on the raise.\nBare metal to production clusters in 48 hours is a strong claim.\nWould be good to connect.",
         dm="Thanks for connecting, Christian.\nAranya's story is mostly on the company page and your co-founder's feed.\nIs your own voice something you want to build now?",
         teardown="Near-silent; headline; infra-buyer content.",
         notes="Co-founders Aryamika Bhatia Ondaatje and Sasivarnan K S."),
    dict(name="Kaitlyn Albertoli", role="Co-founder & CEO", company="Buzz Solutions", region="US", city="Palo Alto",
         url="https://www.linkedin.com/in/kaitlyn-claire-albertoli", confirmed=True,
         trigger="$20M Series A led by S3 Ventures; grid inspection AI", trigger_date="2026-08-04",
         source="https://www.finsmes.com/2026/08/buzz-solutions-raises-20m-in-series-a-funding.html",
         pattern="Milestone-only", last_post="2026-08",
         activity="Posts at milestones and awards: $3.3M round (2022), AI trends (Jan 2024), women in STEM, grid edge (Jan 2025), Series A (Aug 2026). Media interviews (Schwab, Jul 2026).",
         angle="Utilities are a conservative buyer. A steady CEO voice on grid reliability builds the trust that press alone doesn't.",
         score=40,
         connect="Hi Kaitlyn, congrats on the Series A.\nAI for grid inspection matters more every summer.\nWould be good to connect.",
         dm="Thanks for connecting, Kaitlyn.\nYou post at big moments and do interviews well.\nIs a steadier cadence for utility buyers worth it now?",
         teardown="Cadence; utility-buyer content line; interview repurposing.",
         notes="Forbes 30 Under 30 with co-founder Vikhyat Chaudhry."),
    dict(name="Oscar Levy", role="Co-founder & CEO", company="River Markets", region="US", city="",
         url="https://www.linkedin.com/in/oscar-levy", confirmed=True,
         trigger="$8.5M seed led by Haun Ventures with YC and Coinbase Ventures; prediction market prime brokerage", trigger_date="2026-08-11",
         source="https://fortune.com/2026/08/11/exclusive-river-markets-seed-round-prediction-market-trading-tools-institutions/",
         pattern="Emerging writer", last_post="2026-06",
         activity="New to posting: launch story (May 2026), a SpaceX bets post (Jun 2026, 10 comments). Interviews on prediction-market infrastructure.",
         angle="Prediction markets are a hot topic. An early, steady voice for institutions sets the category leader.",
         score=40,
         connect="Hi Oscar, congrats on the seed.\nPrime brokerage for prediction markets is early and interesting.\nWould be good to connect.",
         dm="Thanks for connecting, Oscar.\nYou've just started posting.\nIs keeping it weekly realistic with a new raise to deploy?",
         teardown="Cadence; institutional audience framing; market-commentary series.",
         notes="Co-founder CTO Antonin Parrot."),
    dict(name="Adel Badiri", role="CEO", company="Foundational Industries", region="US", city="",
         url="https://www.linkedin.com/search/results/people/?keywords=Adel%20Badiri%20Foundational%20Industries", confirmed=False,
         trigger="$25M seed led by BoxGroup and Zigg Ventures; AI-native US factories for data centre hardware", trigger_date="2026-08-05",
         source="https://www.finsmes.com/2026/08/foundational-industries-raises-25m-in-seed-funding.html",
         pattern="Not indexed", last_post="",
         activity="No own posts indexed.",
         angle="American reshoring plus AI manufacturing is a strong narrative. A quiet founder is leaving it on the table.",
         score=50,
         connect="Hi Adel, congrats on the seed.\nAI-native factories for data centre hardware in the US is a timely bet.\nWould be good to connect.",
         dm="Thanks for connecting, Adel.\nReshoring and AI manufacturing is a story people want to follow.\nIs your own LinkedIn part of how you tell it?",
         teardown="Confirm profile; build-in-public factory series; hiring.",
         notes="Confirm profile."),
    dict(name="David Lawrence", role="Co-founder & CEO", company="Blue Voice", region="US", city="Boston",
         url="https://www.linkedin.com/search/results/people/?keywords=David%20Lawrence%20Blue%20Voice", confirmed=False,
         trigger="$6M led by SignalFire and Las Olas VC; AI policy guidance for police officers in 225 agencies", trigger_date="2026-08-31",
         source="https://techcrunch.com/2026/08/31/harvard-law-dropout-raises-6m-for-blue-voice-to-build-a-harvey-for-police-officers/",
         pattern="Not indexed", last_post="",
         activity="No own posts indexed. TechCrunch framed him as a Harvard Law dropout.",
         angle="Public-safety buyers are cautious. A founder who explains why he left law school to build this earns trust with chiefs and councils.",
         score=50,
         connect="Hi David, congrats on the raise.\nReal-time policy guidance for officers is a thoughtful use of AI.\nWould be good to connect.",
         dm="Thanks for connecting, David.\nYour reason for starting Blue Voice is a story police leaders would read.\nIs LinkedIn part of how you want to reach them?",
         teardown="Confirm profile; origin story; agency-leader content line.",
         notes="Confirm profile. Sensitive topic, so keep it measured."),
    dict(name="Ian McInnis", role="Co-founder", company="Multiplier", region="US", city="New York",
         url="https://www.linkedin.com/search/results/people/?keywords=Ian%20McInnis%20Multiplier", confirmed=False,
         trigger="$6M seed; moved HQ to Midtown East, New York", trigger_date="2026-08",
         source="https://www.finsmes.com/2026/08/multiplier-raises-usd6m-in-seed-funding.html",
         pattern="Not indexed", last_post="",
         activity="No own posts indexed. Co-founder Ryan Winkler posted the launch (May 2026).",
         angle="New York seed-stage team. The founder who posts gets the first hires and the first customers' attention.",
         score=50,
         connect="Hi Ian, congrats on the seed and the move to New York.\nFollowing what Multiplier is building.\nWould be good to connect.",
         dm="Thanks for connecting, Ian.\nRyan's been the voice of the launch so far.\nIs building your own presence part of the plan?",
         teardown="Confirm profile and role; founder-voice split between co-founders.",
         notes="Confirm profile and who the CEO is. Co-founders Ben Finch and Ryan Winkler."),
]
