"""Cold outreach emails, one per lead, keyed by the lead's name as it appears in the batch data.

Rules (see .claude/skills/gliped-lead-batch/SKILL.md):
- Subject: 2 to 5 words, sentence case, no clickbait, no emojis.
- Body: 50 to 90 words. Hook on their trigger, name the gap, one line on Gliped, one question as the CTA.
- No em dashes, no praise for posts we haven't read, no invented numbers or client results.
- SIGNOFF is appended when rendering, and carries the opt-out line (CASL, PECR, CAN-SPAM).
"""

SIGNOFF = "Prabal\nGliped | LinkedIn personal branding for founders\n\nNot relevant? Reply \"no\" and I won't follow up."
SIGNOFF_FR = "Prabal\nGliped | Personal branding LinkedIn pour dirigeants\n\nPas pertinent? Répondez « non » et je ne vous relancerai pas."

# name -> (subject, body without sign-off)
EMAILS = {
    # ---------------- batch 01 ----------------
    "Ravi Ramachandran": ("Nua after the Series C",
        "Hi Ravi,\n\nCongrats on the $50M Series C.\n\nNua's story gets told at big moments, like the Zero to Scale episode, then it goes quiet. In women's wellness, the founder's voice is a trust asset between campaigns too.\n\nWe run LinkedIn for founders: strategy, writing and posting, built around your voice.\n\nWorth a 15-minute call next week to see what that could look like for you?"),
    "Karishma Rathaur": ("Firi's founder story",
        "Hi Karishma,\n\nNine-minute beauty delivery and a seed round in the same quarter. Strong start.\n\nIn beauty, people buy from people. Right now Firi's story lives in press coverage, not on your LinkedIn, and that's where hires, partners and your next investors will look.\n\nWe build founder brands on LinkedIn, from positioning to weekly posts.\n\nOpen to a quick call to map out your first 90 days?"),
    "Sadra Hosseini": ("Ryft's European push",
        "Hi Sadra,\n\nCongrats on the EUR 23M and the move into Europe.\n\nBuyers in new markets will look you up before they take a call. Your last post was in April 2025, and your FCA licence post shows your audience responds when you do post.\n\nWe help founders turn that into a steady weekly presence without eating their week.\n\nWorth 15 minutes to talk through a Europe-facing plan?"),
    "Erin Kelly": ("askpolly's US launch",
        "Hi Erin,\n\nCongrats on the seed and the US go-to-market push.\n\naskpolly turns social conversations into insight. That kind of data does very well on LinkedIn, and right now none of it goes out under your name to the US buyers you want to reach.\n\nWe build founder brands on LinkedIn, one insight post a week to start.\n\nOpen to a 15-minute call to sketch it out?"),
    "Radhika Patil": ("Cradlewise, new markets",
        "Hi Radhika,\n\nCongrats on the Series A and the international push.\n\nYou've built great press around Cradlewise, but your own LinkedIn has been quiet since mid-2023. New retail partners and parents will look you up first.\n\nWe run LinkedIn for founders: positioning, writing and a steady posting rhythm in your voice.\n\nWould a 15-minute call next week be useful?"),
    "Shourya Agarwal": ("Flam and US CMOs",
        "Hi Shourya,\n\nCongrats on the $40M Series B.\n\nFlam sells interactive content to CMOs, yet your feed is mostly launch announcements. CMOs follow people with a point of view, and yours is the story behind Flam.\n\nWe help founders build that voice on LinkedIn, from strategy to weekly posts.\n\nOpen to 15 minutes to talk through a US-facing plan?"),
    "Jagnoor Singh": ("Your first 100 days",
        "Hi Jagnoor,\n\nCongrats on stepping in as Practo's CEO.\n\nThe first months in the seat are when the market decides what a CEO stands for. Your posts get real engagement (56 comments on #growprofitably), but they come about once a quarter.\n\nWe help CXOs turn that into a steady, credible weekly presence with little time from them.\n\nWorth a 15-minute call to map your first 100 days on LinkedIn?"),
    "Madhulima Tewari": ("VerifAIX, trust first",
        "Hi Madhulima,\n\nCongrats on the $5M seed.\n\nIn chip verification a handful of senior engineers decide who they trust. Right now VerifAIX shows up at events like the RISC-V Summit, but not much on LinkedIn between them.\n\nWe build technical founder brands on LinkedIn, aimed at the few people who matter.\n\nOpen to a quick call to see if it fits?"),
    "Ben Armstrong": ("Back to posting?",
        "Hi Ben,\n\nCongrats on the Series A.\n\nYou used to post regularly on LinkedIn, then it went quiet around 2024. The round was announced by others, not you.\n\nEnterprise security buyers respond to founders they recognise. We help founders get back to a steady rhythm without writing every post themselves.\n\nWorth 15 minutes next week to talk it through?"),
    "Theo Saville": ("The CloudNC story, restarted",
        "Hi Theo,\n\nCongrats on the new round.\n\nIn 2023 you told the CloudNC story yourself on LinkedIn. Since early 2024 the storytelling has moved to the company page.\n\nMachinists and manufacturers follow you, not the logo. We help founders restart and keep that rhythm, with you in control of the voice.\n\nOpen to a 15-minute call to see what a restart could look like?"),
    "Adrian Murray": ("Fisent's story, your voice",
        "Hi Adrian,\n\nCongrats on the raise.\n\nOther people keep telling Fisent's story in interviews, but your own LinkedIn has been quiet since mid-2025. Outcomes-as-a-service is a strong idea to own in public.\n\nWe turn founders' thinking into a steady LinkedIn presence for enterprise buyers.\n\nWorth a 15-minute call to see how?"),
    "Raghav Midha": ("Hiring after the Series A",
        "Hi Raghav,\n\nCongrats on the $20M Series A.\n\nYour LinkedIn is mostly job posts right now. Strong engineers pick founders whose thinking they've already seen.\n\nWe help technical founders write about the problem they're solving, so hiring and fleet buyers come to them.\n\nOpen to 15 minutes to talk it through?"),
    "Doug Schweitzer": ("From minister to founder",
        "Hi Doug,\n\nCongrats on Ultimarii's Series A.\n\nPeople know you from your years in government. Fewer know you yet as the founder speeding up infrastructure approvals with AI, and your LinkedIn still reads like the old role.\n\nWe help founders reposition on LinkedIn with a steady voice aimed at energy and infrastructure leaders.\n\nWorth a 15-minute call?"),
    "Gabriel Rivest": ("Scopia's next chapter",
        "Hi Gabriel,\n\nCongrats on closing the pre-seed.\n\nIn medtech, surgeons and partners check the founder before the product. Right now you post at milestones only.\n\nWe build founder brands on LinkedIn, in English, French or both, aimed at clinicians and partners.\n\nOpen to a quick call to see what that could look like for Scopia?"),
    "David Lighton": ("Bootstrapped to Series A",
        "Hi David,\n\nCongrats on the Series A. Bootstrapping to that point in payments is rare.\n\nThat's a story banks and platforms want to hear, but your LinkedIn has been quiet since 2023.\n\nWe help founders turn their thinking into a steady LinkedIn presence, aimed at the partners they need.\n\nWorth 15 minutes to talk it through?"),
    "Leo Crowe": ("Weekly, not quarterly",
        "Hi Leo,\n\nCongrats on the pre-seed.\n\nYou already write about partnerships on LinkedIn, and your buyers live there. The gap is rhythm: a post every few months instead of every week.\n\nWe help founders keep a weekly cadence in their own voice without it eating their week.\n\nOpen to a quick call?"),
    "Alex Harland": ("AI governance, out loud",
        "Hi Alex,\n\nCongrats on the round.\n\nYou have a clear point of view on AI governance, and CISOs and GCs need to hear it more than twice a year.\n\nWe help founders turn that point of view into a steady LinkedIn presence that builds the category with them in it.\n\nWorth a 15-minute call next week?"),
    "Shishir Bankapur": ("Explaining Helogen",
        "Hi Shishir,\n\nCongrats on the seed.\n\nSpace biomanufacturing needs a lot of explaining to investors, talent and early customers. \"The next industrial revolution isn't on earth\" is a good frame, and it deserves a regular slot.\n\nWe help frontier founders build an explainer-led presence on LinkedIn.\n\nOpen to a quick call to see how?"),
    "Shashank ND": ("The chairman's voice",
        "Hi Shashank,\n\nCongratulations on the new role at Practo.\n\nMoving from CEO to Executive Chairman changes what people expect to hear from you: capital, AI and the long-term bets, not operations.\n\nWe help senior leaders shape that narrative on LinkedIn, with a light touch on their time.\n\nWould a short call be useful, with you or whoever runs your comms?"),
    "Ilan Zerbib": ("Your weekly hours back",
        "Hi Ilan,\n\nCongrats on the Series A.\n\nYou're one of the few founders who posts consistently. That usually costs hours a week that a CEO of a fast-growing company doesn't have.\n\nWe keep founders' voice and rhythm while taking the writing and repurposing off their plate.\n\nWorth 15 minutes to see what you'd get back?"),

    # ---------------- batch 02 ----------------
    "Aniket Shah": ("Swish's founder story",
        "Hi Aniket,\n\nCongrats on the $24M round.\n\nQuick commerce is crowded, and Swish's story mostly shows up at raises and hiring posts. The founder who explains why 10-minute fresh food works wins the best hires and the press in between.\n\nWe build founder brands on LinkedIn, from positioning to weekly posts.\n\nOpen to a 15-minute call next week?"),
    "Sunil Gupta": ("Quantum-safe, explained",
        "Hi Sunil,\n\nCongrats on the Rs 200 Cr Series A1.\n\nYour LinkedIn announces QNu's milestones well. What most CISOs and government buyers still need is the why: why quantum-safe, why now.\n\nWe help deep-tech founders build that voice on LinkedIn, steadily and credibly.\n\nWorth a 15-minute call to see how it could work for you?"),
    "Prashant Shah": ("Your credentials, visible",
        "Hi Prashant,\n\nCongrats on the pre-Series A.\n\nYou carry more technical-analysis credentials than most people posting about markets, yet they barely show on LinkedIn. Retail traders follow people, not platforms.\n\nWe turn founders' expertise into a steady LinkedIn presence that pulls users to the product.\n\nOpen to a quick call?"),
    "Abhijit (AB) Gupta": ("Pizza Bakery, next cities",
        "Hi AB,\n\nCongrats on the Rs 532 Cr round from Artal.\n\nYou built The Pizza Bakery without growth capital. That's a founder story F&B operators, landlords and new-city hires will follow, and it hasn't been on your LinkedIn since 2023.\n\nWe build founder brands on LinkedIn around stories like that.\n\nWorth 15 minutes to talk it through?"),
    "Karan Jain": ("Profitable from month one",
        "Hi Karan,\n\nCongrats on the Uber-led round.\n\nA second-time founder, profitable from month one, backed twice by Uber. Very few people in mobility can tell that story, and right now you're not telling it on LinkedIn.\n\nWe build founder brands on LinkedIn, from positioning to weekly posts.\n\nOpen to a 15-minute call next week?"),
    "Abhishek Murarka": ("Cooling as a category",
        "Hi Abhishek,\n\nCongrats on the pre-Series A.\n\nCooling-as-a-service is a new category, and businesses buying it want to trust the operator behind it. Right now Circolife's page does the talking.\n\nWe help founders build their own voice on LinkedIn around the category they're creating.\n\nWorth a quick call to see if it fits?"),
    "Sneha Priya Reddy": ("UniqYou's launch voice",
        "Hi Sneha,\n\nCongrats on the seed, and on backers like the Myntra founders.\n\nIn fashion, people buy into the founder's taste first. A founder-led LinkedIn at launch often costs less than paid acquisition and brings hires with it.\n\nWe build founder brands on LinkedIn from day one.\n\nOpen to 15 minutes to plan your first 90 days?"),
    "Ankit Joshi": ("TRUE ARTIS, trust first",
        "Hi Ankit,\n\nCongrats on the seed.\n\nIn aesthetic surgery, patients check who's behind the clinic before they book. A founder who talks openly about safety and standards sets TRUE ARTIS apart.\n\nWe build founder brands on LinkedIn, carefully and within medical advertising norms.\n\nWorth a 15-minute call?"),
    "Devang Kumar": ("Greenwave and ESG buyers",
        "Hi Devang,\n\nCongrats on the OeEB financing.\n\nThe brand sustainability leads you'll want as offtake partners are on LinkedIn. A founder voice on closed-loop PET recycling gives them a reason to call you first.\n\nWe build founder brands on LinkedIn, aimed at the buyers that matter.\n\nOpen to a quick call?"),
    "Avni Jain": ("24 prototypes is content",
        "Hi Avni,\n\nCongrats on the pre-seed.\n\n24 prototypes and 900 hours of wear testing to get a heel that doesn't hurt. That build story is content most D2C founders would kill for.\n\nWe help founders turn stories like that into a steady LinkedIn presence, sized for an early-stage budget.\n\nWorth a 15-minute call?"),
    "Charlie Bullock": ("Scan.com's US chapter",
        "Hi Charlie,\n\nCongrats on the Series C and the US push.\n\nYour posts land well when you post, but the last one I could find was March 2025. US health systems and partners are meeting you for the first time now.\n\nWe help founders keep a steady, credible LinkedIn presence, working with your comms team.\n\nWorth a 15-minute call?"),
    "Charlie Cook": ("Rightcharge across Europe",
        "Hi Charlie,\n\nCongrats on the raise and the Visa partnership.\n\nYou've got a real voice on LinkedIn, humour included. It just shows up a few times a year, and European fleet managers don't know you yet.\n\nWe help founders keep a weekly rhythm in their own voice without it eating their week.\n\nOpen to a quick call?"),
    "Koji Muto": ("Making Ki 13 stick",
        "Hi Koji,\n\nCongrats on the seed and the new Ki 13 name.\n\nA rebrand only sticks when people hear the story behind it, and right now you post mainly at milestones.\n\nWe help deep-tech founders build a steady LinkedIn presence that explains the science and the ambition.\n\nWorth 15 minutes to talk it through?"),
    "Francisco Vigo": ("Your own AI visibility",
        "Hi Francisco,\n\nCongrats on the seed.\n\nOdd one for someone in AI visibility: LinkedIn posts are one of the sources AI models draw on, and right now the geoSurge company page does most of the talking.\n\nWe build founder brands on LinkedIn, so the founder shows up too.\n\nOpen to a quick call?"),
    "Callum Adamson": ("Orbital, in your words",
        "Hi Callum,\n\nCongrats on the round with KBR and Databricks.\n\nEnergy operators buy from people they trust, and a CEO voice on AI in refining is rare. Right now Orbital's story lives on the company page.\n\nWe help founders build a steady LinkedIn presence aimed at operators.\n\nWorth a 15-minute call?"),
    "Lestat McCree": ("Healf, week by week",
        "Hi Lestat,\n\nCongrats on the round and the Germany launch.\n\nYour AI adoption piece got people talking, but it's one of only a few posts. With international growth and press momentum, a steady rhythm compounds.\n\nWe help founders keep a weekly LinkedIn presence in their own voice, alongside their comms team.\n\nOpen to a quick call?"),
    "Jon Steinback": ("Distribution, not writing",
        "Hi Jon,\n\nCongrats on the Marker launch.\n\nYou write your own posts and should. For most writer-founders the harder part is distribution: cadence, formats and reaching buyers, not only other writers.\n\nThat's the part we can help with at Gliped, with you still doing the writing.\n\nWorth a 15-minute chat?"),
    "Stephen Cowley": ("Keeping it weekly",
        "Hi Stephen,\n\nCongrats on the seed.\n\nYou've started posting customer stories on LinkedIn, which is the right instinct for reaching pharma commercial teams. The hard part is keeping it going every week.\n\nWe help founders do exactly that, in their own voice.\n\nOpen to a quick call?"),
    "Steve Rimmer": ("Tickets for Good's story",
        "Hi Steve,\n\nCongrats on the new funding.\n\nGetting surplus tickets to key workers is the kind of story people share, and venues and promoters respond to the person behind it.\n\nWe build founder brands on LinkedIn around stories like yours.\n\nWorth a 15-minute call?"),
    "Ismaeel Bashir": ("Expanse on both sides",
        "Hi Ismaeel,\n\nCongrats on the raise.\n\nAI infrastructure is noisy, and with teams in the UK and US you need buyers on both sides to recognise you. A clear founder point of view on LinkedIn does that.\n\nWe build founder brands on LinkedIn, from positioning to weekly posts.\n\nOpen to a quick call?"),
    "Jason Liao": ("Mundo's founder voice",
        "Hi Jason,\n\nCongrats on the Series A.\n\nMost of Mundo's story online comes from press and your co-founders. Model teams and top researchers want to hear from the CEO too.\n\nWe build founder brands on LinkedIn for technical founders, aimed at buyers and hires.\n\nWorth a 15-minute call?"),
    "David S. Bennahum": ("Onix and your voice",
        "Hi David,\n\nCongrats on the pre-seed.\n\nOnix is built on experts owning their voice. Yours shows up on LinkedIn every few months.\n\nYou can clearly write, so this isn't about ghostwriting. We help founders with cadence, formats and distribution.\n\nOpen to a quick call?"),
    "Kyle Braatz": ("Fullscript's CEO voice",
        "Hi Kyle,\n\nCongrats on the L Catterton and Altas investment.\n\nYour LinkedIn is mostly Fullscript updates. Practitioners and partners would follow a stronger CEO point of view on where integrative health is going.\n\nWe support executive LinkedIn presence alongside in-house comms teams.\n\nWorth a 15-minute call?"),
    "LP Maurice": ("Terra Mobility, restarted",
        "Hi LP,\n\nCongrats on the financing and the Terra Mobility launch.\n\nYour LatAm and Africa posts drew 60+ comments, then your LinkedIn went quiet in 2024. A new parent company is the moment to restart.\n\nWe help founders get back to a steady rhythm without writing every post themselves.\n\nOpen to a quick call?"),
    "Stéphane Garneau": ("Micrologic et le cloud souverain",
        "Bonjour Stéphane,\n\nFélicitations pour le financement.\n\nLe cloud souverain est un sujet d'actualité, et vous publiiez régulièrement là-dessus jusqu'en 2024. Une voix de PDG, en français et en anglais, positionne Micrologic auprès des acheteurs publics.\n\nChez Gliped, nous bâtissons la présence LinkedIn des dirigeants.\n\nUn appel de 15 minutes la semaine prochaine?"),
    "Sanja Fidler": ("Veeda, from NVIDIA",
        "Hi Sanja,\n\nCongrats on launching Veeda.\n\nYour LinkedIn has been NVIDIA research. Veeda is a new story, and the researchers you want to hire will look for it in your feed.\n\nWe help technical founders build a founder narrative on LinkedIn without pulling them away from the work.\n\nWorth a short call?"),
    "Kimia Hamidi": ("NationGraph, steadily",
        "Hi Kimia,\n\nYour NationGraph launch post drew a lot of discussion. Since then you post a few times a year.\n\nPublic-sector buyers take time to trust a vendor, and a steady founder voice shortens that.\n\nWe help founders keep a regular LinkedIn rhythm in their own voice.\n\nOpen to a quick call when timing suits?"),
    "Darren Hill": ("Legio and campus leaders",
        "Hi Darren,\n\nCongrats on the seed.\n\nCampus safety leaders are a tight community, and they buy on trust. A founder voice on LinkedIn about safety operations sets Legio apart.\n\nWe build founder brands on LinkedIn aimed at the buyers that matter.\n\nWorth a 15-minute call?"),
    "Kelvin Cui": ("Peripheral on LinkedIn",
        "Hi Kelvin,\n\nCongrats on the seed.\n\nYour product is very visual, which suits LinkedIn. Founder posts with product clips double as marketing to sports media buyers.\n\nWe build founder brands on LinkedIn, from positioning to weekly posts.\n\nOpen to a quick call?"),
    "Sumit Ajwani": ("MakeOS, founder-led",
        "Hi Sumit,\n\nCongrats on launching MakeOS.\n\nThe launch is on the Makers page, but your own feed is quiet. Producers and agencies live on LinkedIn, and they follow people.\n\nWe build founder brands on LinkedIn around launches like this one.\n\nWorth a 15-minute call?"),
    "Baker Shogry": ("Light's founder voice",
        "Hi Baker,\n\nCongrats on the $46M Series A.\n\nEnergy is a trust category, and your LinkedIn has been nearly silent. Brands deciding whether to launch their own electricity plan will look you up.\n\nWe build founder brands on LinkedIn, from positioning to weekly posts.\n\nOpen to a quick call next week?"),
    "Guy Shahar": ("Your weekly hours back",
        "Hi Guy,\n\nCongrats on the Series A.\n\nYou post more consistently than most founders. That usually costs hours a week, right when Blee is scaling.\n\nWe keep founders' voice and rhythm while taking the writing and repurposing off their plate.\n\nWorth 15 minutes to see what you'd get back?"),
    "Michael LaFramboise": ("Aurelius, every week",
        "Hi Michael,\n\nCongrats on the $40M Series A.\n\nYour defence-tech posts get attention when they land, every month or two. Weekly would help both hiring and customers.\n\nWe help founders keep that rhythm in their own voice, with care around what defence content can say.\n\nOpen to a quick call?"),
    "Noah Schochet": ("TerraFirma, weekly",
        "Hi Noah,\n\nCongrats on the Series A.\n\nYou post with a clear point of view every couple of months. Weekly turns that into a category voice for construction.\n\nWe help founders keep a weekly rhythm in their own voice without it eating their week.\n\nWorth a 15-minute call?"),
    "Christian Bhatia Ondaatje": ("Aranya out of stealth",
        "Hi Christian,\n\nCongrats on the raise.\n\nAranya's story is on the company page and your co-founder's feed. Infrastructure buyers want to hear from the CEO, and yours has been quiet since 2024.\n\nWe build founder brands on LinkedIn for technical founders.\n\nOpen to a quick call?"),
    "Kaitlyn Albertoli": ("Buzz and utility buyers",
        "Hi Kaitlyn,\n\nCongrats on the Series A.\n\nYou post at big moments and do interviews well. Utilities are conservative buyers, and a steady CEO voice on grid reliability builds trust that press alone doesn't.\n\nWe help founders turn interviews and milestones into a weekly LinkedIn rhythm.\n\nWorth a 15-minute call?"),
    "Oscar Levy": ("River Markets, weekly",
        "Hi Oscar,\n\nCongrats on the seed.\n\nYou've just started posting about prediction markets. The founder who shows up every week for institutions becomes the category voice.\n\nWe help founders keep that rhythm while they deploy a new round.\n\nOpen to a quick call?"),
    "Adel Badiri": ("Foundational's story",
        "Hi Adel,\n\nCongrats on the $25M seed.\n\nAmerican reshoring plus AI-native factories is a story people want to follow, and right now you're not telling it on LinkedIn.\n\nWe build founder brands on LinkedIn, from positioning to weekly posts, including build-in-public.\n\nWorth a 15-minute call?"),
    "David Lawrence": ("Blue Voice's why",
        "Hi David,\n\nCongrats on the raise.\n\nWhy you left law school to build Blue Voice is a story police leaders and councils would read, and it builds the trust public-safety buyers need.\n\nWe build founder brands on LinkedIn, carefully and in a measured tone.\n\nOpen to a quick call?"),
    "Ian McInnis": ("Multiplier in New York",
        "Hi Ian,\n\nCongrats on the seed and the move to New York.\n\nRyan has been the voice of the launch so far. At seed stage, the founder who posts gets the first hires' and first customers' attention.\n\nWe build founder brands on LinkedIn, from positioning to weekly posts.\n\nWorth a 15-minute call?"),
}


def render(name):
    subject, body = EMAILS[name]
    sign = SIGNOFF_FR if name == "Stéphane Garneau" else SIGNOFF
    return subject, f"{body}\n\n{sign}"
